---
title: Sense HAT-sensoren
hero_image: images / banner.png
description: Leer hoe je sensorgegevens van de Sense HAT kunt lezen met Python en hoe je pixel art kunt maken met de pixeldisplay van de Sense HAT
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Introductie
  - 
    title: Test the Sense HAT
  - 
    title: Faces
  - 
    title: Make it hot
