---
title: Sense HAT सेंसर
hero_image: images/banner.png
description: Sense HAT द्वारा Python की मदद से सेंसर डाटा पढ़े, और Sense HAT के पिक्सेल डिस्प्ले पर पिक्सेल कला बनाए
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: परिचय
  - 
    title: Test the Sense HAT
  - 
    title: Faces
  - 
    title: Make it hot
