---
title: حسگرهای Sense HAT
hero_image: images/banner.png
description: یادگیری نحوه‌ی خواندن اطلاعات حسگر از Sense HAT با استفاده از پایتون و نحوه‌ی ایجاد پیکسل بر روی نمایشگر پیکسلی Sense HAT
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: معرفی
  - 
    title: Test the Sense HAT
  - 
    title: Faces
  - 
    title: Make it hot
