---
title: Sense HAT Sensoren
hero_image: Bilder / Banner.png
description: Lernen Sie, Sensordaten aus dem Sense HAT mit Python zu lesen und wie Sie Pixelgrafiken auf der Pixelanzeige des Sense HATs erstellen
theme: rot
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: Programmierung-0, Phys-Comp-0
interests: "physikalische Datenverarbeitung"
technologies: "Sinneshut, physikalisches Rechnen, Python"
site_areas: ""
steps:
  - 
    title: Einführung
  - 
    title: Was wirst du brauchen
  - 
    title: Teste die Sense-HUT
  - 
    title: Gesichter
  - 
    title: Heiß machen
