---
title: Sense HAT Sensoren
hero_image: images/banner.png
description: Lerne, mit Python Sensordaten aus dem Sense HAT zu lesen und wie du Pixelgrafiken auf der Pixelanzeige des Sense HATs erstellst
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "physical computing"
technologies: "sense-hat, physical computing, python"
site_areas: ""
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Teste das Sense-HAT
  - 
    title: Gesichter
  - 
    title: Mach es heiß
