---
title: Sense HAT-sensoren
hero_image: images / banner.png
description: Leer hoe je sensorgegevens van de Sense HAT kunt lezen met Python en hoe je pixelart kunt maken op de pixelweergave van de SENS HAT.
theme: rood
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: programming-0, phys-comp-0
interests: "fysiek computergebruik"
technologies: "sense-hat, fysieke computergebruik, python"
site_areas: ""
steps:
  - 
    title: Invoering
  - 
    title: Wat je nodig zult hebben
  - 
    title: Test de Sense HAT
  - 
    title: gezichten
  - 
    title: Maak het heet
