---
title: Sense HAT érzékelők
hero_image: images / banner.png
description: Tanulja meg a Sensor adatok olvasását a Sense HAT-ból Python segítségével, és hogyan készítsen pixel artot a Sense HAT képpont kijelzőjén
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Bevezetés
  - 
    title: Test the Sense HAT
  - 
    title: Faces
  - 
    title: Make it hot
