---
title: Les capteurs du Sense HAT
hero_image: images / banner.png
description: Apprend à lire les données des capteurs du Sense HAT en utilisant Python, et à créer du pixel art sur l'écran d'affichage à pixels du Sense HAT
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Introduction
  - 
    title: Tester le Sense HAT
  - 
    title: Visages
  - 
    title: Réchauffe-le
