---
title: I sensori del Sense HAT
hero_image: images/banner.png
description: Impara a leggere i dati dei sensori da HAT Sense usando Python e come creare pixel art sul display dei pixel di Sense HAT
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Introduzione
  - 
    title: Test the Sense HAT
  - 
    title: Faces
  - 
    title: Make it hot
